const ingredients=['Salat','Tomaten','Weißkraut','Rotkraut','Zwiebeln'];
const sauces=['Knoblauchsoße','Kräutersoße','Cocktailsoße','Scharfe Soße'];
const basicSauces=['Ketchup','Mayonnaise','Senf'];
const menuDrinks=['Cola','Fanta','Sprite','Uludağ','Ayran','Wasser'];
const extras=[['Käse',1],['Peperoni',1],['Jalapeños',1],['Extra Fleisch',2.5],['Extra Soße',1]];
let cart=[],current=null,mode='Abholung',payment='Barzahlung';
const deliveryServiceFee=2;
function orderAmounts(){const subtotal=cart.reduce((s,x)=>s+x.price,0),fee=mode==='Lieferung'&&cart.length?deliveryServiceFee:0;return {subtotal,fee,total:subtotal+fee}}
function updateOrderSummary(){const amounts=orderAmounts();document.querySelector('#cartTotal').textContent=euro(amounts.total);document.querySelector('#floatingTotal').textContent=euro(amounts.total);document.querySelector('#serviceFeeRow').hidden=mode!=='Lieferung'||!cart.length;document.querySelector('#serviceFeeValue').textContent=euro(amounts.fee);document.querySelector('#goodsSubtotal').textContent=euro(amounts.subtotal)}
const euro=n=>n.toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const itemBasePrice=p=>p.price+(p.deposit||0);
const isHalalProduct=p=>['offer','menu','bowl','doener','dueruem','box'].includes(p.category)||p.id==='nuggets'||p.id==='extra-meat';
const grid=document.querySelector('#productGrid');

function renderProducts(filter='all'){
 grid.innerHTML=products.filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="product visual"><div class="product-image ${p.icon?'symbol-image':''}">${p.icon?`<span aria-hidden="true">${p.icon}</span>`:`<img src="assets/products/${p.image}" alt="${p.name}" loading="lazy">`}</div><div class="product-body"><span class="product-tag">${p.tag}</span>${isHalalProduct(p)?'<span class="halal-badge">✓ 100 % Halal</span>':''}<h3>${p.name}</h3><p>${p.desc}</p><div class="product-footer"><strong>${p.small||p.category==='menu'?'ab ':''}${euro(p.small||itemBasePrice(p))}${p.deposit?'<small> inkl. Pfand</small>':''}</strong><button data-product="${p.id}">${p.config||p.sizes?'Konfigurieren':'Hinzufügen'} +</button></div></div></article>`).join('');
}
function chip(type,value,label,checked=false,extra=''){return `<label class="chip"><input type="${type}" name="${value.startsWith('size')?'size':value.startsWith('sauce')?'sauce':value.startsWith('drink')?'drink':'option'}" value="${value}" ${checked?'checked':''} data-extra="${extra}"><span>${label}</span></label>`}
function groupedCart(){
 const groups=[];
 cart.forEach((item,index)=>{const key=[item.name,item.price,item.size,item.details,item.recipient||''].join('|');const found=groups.find(group=>group.key===key);if(found){found.quantity+=1;found.indices.push(index)}else groups.push({...item,key,quantity:1,indices:[index]})});
 return groups;
}
function openConfig(id){
 current=products.find(p=>p.id===id); document.querySelector('#configTitle').textContent=current.name; document.querySelector('#configDesc').textContent=current.desc; document.querySelector('#configImage').src=`assets/products/${current.image}`; document.querySelector('#configImage').alt=current.name;
 let html='';
 if(current.small)html+=`<div class="option-group"><h3>Portion wählen</h3><div class="chips">${chip('radio','size-large',`Ganzer Döner · ${euro(current.price)}`,true,current.price)}${chip('radio','size-small',`Halber Döner · ${euro(current.small)}`,false,current.small)}</div></div>`;
 if(current.sizes)html+=`<div class="option-group"><h3>${current.category==='menu'||current.category==='offer'?'Variante wählen':'Menge wählen'}</h3><div class="chips">${current.sizes.map((s,i)=>chip('radio',`size-${i}`,`${s[0]} · ${euro(s[1])}`,i===0,s[1])).join('')}</div></div>`;
 if(current.drinks)html+=`<div class="option-group"><h3>Inklusivgetränk wählen</h3><div class="chips">${menuDrinks.map((x,i)=>chip('radio',`drink-${i}`,x,i===0)).join('')}</div></div>`;
 if(current.sauceMode){const free=current.sauceMode==='oneFree';html+=`<div class="option-group"><h3>${free?'Dip-Soßen · 1 gratis':'Dip-Soßen · je 0,50 €'}</h3><div class="chips">${basicSauces.map((x,i)=>`<label class="chip"><input type="checkbox" name="sauce" value="basic-${i}" data-sauce-tier="basic"><span>${x}${free?'':` · +${euro(.5)}`}</span></label>`).join('')}</div>${free?'<p class="option-hint">Die erste Auswahl ist gratis, jede weitere kostet 0,50 €.</p>':''}</div><div class="option-group"><h3>Hausgemachte Soßen <small>(je +1,00 €)</small></h3><div class="chips">${sauces.map((x,i)=>chip('checkbox',`sauce-extra-${i}`,`${x} · +${euro(1)}`,false,1)).join('')}</div></div>`}
 if(current.config==='coffee')html+=`<div class="option-group"><h3>Kostenlose Wünsche</h3><div class="chips">${chip('checkbox','Milch','Milch')}${chip('checkbox','Zucker','Zucker')}</div></div>`;
 else if(current.config==='box')html+=`<div class="option-group"><h3>Soße wählen <small>(optional)</small></h3><div class="chips">${sauces.map((x,i)=>chip('checkbox',`sauce-${i}`,x,false)).join('')}</div><p class="option-hint">Erneut antippen zum Abwählen · keine Auswahl = ohne Soße</p></div><div class="option-group"><h3>Extras</h3><div class="chips">${extras.filter(x=>x[0]==='Extra Fleisch'||x[0]==='Extra Soße').map(x=>chip('checkbox',x[0],`${x[0]} · +${euro(x[1])}`,false,x[1])).join('')}</div></div>`;
 else if(current.config===true)html+=`<div class="option-group"><div class="option-heading"><h3>Zutaten wählen</h3><button type="button" class="select-all" data-select-all>Mit allem</button></div><div class="chips">${ingredients.map(x=>chip('checkbox',x,x,false)).join('')}</div></div><div class="option-group"><h3>Soße wählen <small>(optional)</small></h3><div class="chips">${sauces.map((x,i)=>chip('checkbox',`sauce-${i}`,x,false)).join('')}</div><p class="option-hint">Erneut antippen zum Abwählen · keine Auswahl = ohne Soße</p></div><div class="option-group"><h3>Extras</h3><div class="chips">${extras.map(x=>chip('checkbox',x[0],`${x[0]} · +${euro(x[1])}`,false,x[1])).join('')}</div></div>`;
 html+=`<div class="option-group person-option"><label for="itemRecipient"><strong>Für wen ist das?</strong><input id="itemRecipient" type="text" maxlength="30" placeholder="Optional, z. B. Fuat oder Mama"></label><p class="option-hint">Bei mehreren Varianten erzeugen wir sonst automatisch eine Nummer.</p></div>`;
 if(hasDoenerSaucePricing(current))html=html.replace('Soße wählen <small>(optional)</small>','Soße wählen <small>1. gratis · jede weitere +0,50 €</small>');
 document.querySelector('#configForm').innerHTML=html; document.querySelector('#configOverlay').hidden=false; document.body.style.overflow='hidden'; updateConfigPrice();
}
function hasDoenerSaucePricing(p){return ['doener','dueruem','offer','menu'].includes(p.category)&&p.config===true}
function sauceTierPrice(checked){const count=checked.filter(i=>i.dataset.sauceTier==='basic').length;const dips=current.sauceMode==='oneFree'?Math.max(0,count-1)*.5:current.sauceMode==='paidBasic'?count*.5:0;const normal=checked.filter(i=>/^sauce-\d+$/.test(i.value)).length;return dips+(hasDoenerSaucePricing(current)?Math.max(0,normal-1)*.5:0)}
function syncSelectAll(checked){const button=document.querySelector('#configForm [data-select-all]');if(!button)return;const all=ingredients.every(value=>checked.some(input=>input.value===value));button.textContent=all?'✓ Mit allem':'Mit allem';button.classList.toggle('active',all);button.setAttribute('aria-pressed',String(all))}
function updateConfigPrice(){let base=itemBasePrice(current);const size=document.querySelector('#configForm input[name=size]:checked'),checked=[...document.querySelectorAll('#configForm input:checked')];syncSelectAll(checked);if(size)base=Number(size.dataset.extra)+(current.deposit||0);checked.filter(i=>i.type==='checkbox').forEach(i=>base+=Number(i.dataset.extra||0));base+=sauceTierPrice(checked);document.querySelector('#configPrice').textContent=euro(base)}
function addConfigured(){
 const checked=[...document.querySelectorAll('#configForm input:checked')]; let price=itemBasePrice(current); const size=checked.find(i=>i.name==='size');if(size)price=Number(size.dataset.extra)+(current.deposit||0);checked.filter(i=>i.type==='checkbox').forEach(i=>price+=Number(i.dataset.extra||0));price+=sauceTierPrice(checked);
 const allIngredients=ingredients.every(x=>checked.some(i=>i.value===x));
 const detailParts=checked.filter(i=>!i.value.startsWith('size')&&!(allIngredients&&ingredients.includes(i.value))).map(i=>i.value.startsWith('sauce')||i.value.startsWith('drink')||i.dataset.sauceTier?i.nextElementSibling.textContent:i.value);
 if(allIngredients)detailParts.unshift('Mit allem');
 const normalSauces=checked.filter(i=>/^sauce-\d+$/.test(i.value)).length;
 if(hasDoenerSaucePricing(current)&&normalSauces>1)detailParts.push(`Soßen-Aufpreis: +${euro((normalSauces-1)*.5)}`);
 let details=detailParts.join(', ');
 if(current.deposit)details+=(details?', ':'')+`inkl. ${euro(current.deposit)} Pfand`;
 const recipient=document.querySelector('#itemRecipient').value.trim();cart.push({name:current.name,price,details,size:size?size.nextElementSibling.textContent.split(' · ')[0]:'',recipient});closeOverlay('configOverlay');updateCart();
}
function quickAdd(id){const p=products.find(x=>x.id===id);cart.push({name:p.name,price:itemBasePrice(p),details:p.deposit?`inkl. ${euro(p.deposit)} Pfand`:'',size:''});updateCart()}
function updateCart(){const total=cart.reduce((s,x)=>s+x.price,0);document.querySelector('#cartCount').textContent=cart.length;document.querySelector('#floatingCount').textContent=cart.length;updateOrderSummary();document.querySelector('#floatingCart').hidden=!cart.length;const send=document.querySelector('#sendWhatsapp'),blocked=mode==='Lieferung'&&total<22;send.classList.toggle('minimum-blocked',blocked);send.title=blocked?'Mindestbestellwert für Lieferung: 22,00 €':''}
function openCart(){
 const groups=groupedCart();document.querySelector('#cartItems').innerHTML=cart.length?groups.map((x,i)=>{const same=groups.filter(g=>g.name===x.name),auto=same.length>1?`${x.name} ${same.indexOf(x)+1}`:'';return `<div class="cart-item"><div>${x.recipient||auto?`<span class="item-label">${x.recipient?`Für: ${x.recipient}`:auto}</span>`:''}<strong>${x.quantity}× ${x.name}</strong><small>${[x.size,x.details].filter(Boolean).join(' · ')}</small></div><strong>${euro(x.price*x.quantity)}</strong><button class="remove" data-remove="${x.indices[x.indices.length-1]}" aria-label="Ein Stück entfernen">×</button></div>`}).join(''):'<div class="empty">Dein Warenkorb ist noch leer.</div>';
 updateOrderSummary();document.querySelector('#cartOverlay').hidden=false;document.body.style.overflow='hidden';
}
function closeOverlay(id){document.querySelector('#'+id).hidden=true;document.body.style.overflow=''}
function whatsapp(){
 if(!cart.length)return;const orderTotal=cart.reduce((s,x)=>s+x.price,0);if(mode==='Lieferung'&&orderTotal<22){document.querySelector('#minimumMissing').textContent=euro(22-orderTotal);document.querySelector('#minimumOverlay').hidden=false;document.body.style.overflow='hidden';return}const name=document.querySelector('#customerName').value.trim()||'Nicht angegeben',time=document.querySelector('#customerTime').value||'So bald wie möglich',address=document.querySelector('#customerAddress').value.trim(),note=document.querySelector('#customerNote').value.trim();
 const groups=groupedCart();const lines=groups.map(x=>{const same=groups.filter(g=>g.name===x.name),auto=same.length>1?`${x.name} ${same.indexOf(x)+1}`:'';return `${x.quantity}× ${x.name}${x.recipient?` – für ${x.recipient}`:auto?` – ${auto}`:''} – ${euro(x.price*x.quantity)}\n${[x.size,x.details].filter(Boolean).join(' · ')}`}).join('\n\n');const amounts=orderAmounts();const total=euro(amounts.total);const text=`Hallo Bro's Döner! 👋\n\nIch möchte bestellen:\n\n${lines}\n\n${mode==='Lieferung'?`Warenwert: ${euro(amounts.subtotal)}\nServicegebühr Lieferung: ${euro(amounts.fee)}\n`:''}*Gesamt: ${total}*\n\n${mode}: ${time}\nZahlung: ${payment}\nName: ${name}${address?`\nAdresse: ${address}`:''}${note?`\nHinweis: ${note}`:''}\n\nBitte kurz bestätigen. Danke!`;
 window.open(`https://wa.me/491785190405?text=${encodeURIComponent(text)}`,'_blank','noopener');
}
renderProducts();
document.addEventListener('click',e=>{const p=e.target.closest('[data-product]');if(p){const item=products.find(x=>x.id===p.dataset.product);item.config||item.sizes?openConfig(item.id):quickAdd(item.id)}const all=e.target.closest('[data-select-all]');if(all){document.querySelectorAll('#configForm input[type=checkbox]').forEach(input=>{if(ingredients.includes(input.value))input.checked=true});all.textContent='Alles ausgewählt';updateConfigPrice()}const c=e.target.closest('[data-close]');if(c)closeOverlay(c.dataset.close);const r=e.target.closest('[data-remove]');if(r){cart.splice(Number(r.dataset.remove),1);updateCart();openCart()}const f=e.target.closest('[data-filter]');if(f){document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));f.classList.add('active');renderProducts(f.dataset.filter)}const m=e.target.closest('[data-mode]');if(m){mode=m.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===m));document.querySelector('#addressLabel').hidden=mode!=='Lieferung';document.querySelector('#deliveryNote').hidden=mode!=='Lieferung';const card=document.querySelector('[data-payment="Kartenzahlung"]'),bar=document.querySelector('[data-payment="Barzahlung"]');card.disabled=mode==='Lieferung';document.querySelector('#paymentHint').textContent=mode==='Lieferung'?'Kartenzahlung ist bei Lieferung momentan nicht verfügbar.':'Kartenzahlung ist bei Abholung möglich.';if(mode==='Lieferung'&&payment==='Kartenzahlung'){payment='Barzahlung';card.classList.remove('active');bar.classList.add('active')}updateCart()}const pay=e.target.closest('[data-payment]');if(pay&&!pay.disabled){payment=pay.dataset.payment;document.querySelectorAll('[data-payment]').forEach(x=>x.classList.toggle('active',x===pay))}});
document.querySelector('#configForm').addEventListener('change',updateConfigPrice);document.querySelector('#addToCart').addEventListener('click',addConfigured);document.querySelector('#floatingCart').addEventListener('click',openCart);document.querySelector('#cartTop').addEventListener('click',openCart);document.querySelector('#sendWhatsapp').addEventListener('click',whatsapp);document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)closeOverlay(o.id)}));

const hoursTrigger=document.querySelector('#hoursTrigger'),hoursRoll=document.querySelector('#hoursRoll'),quickHours=document.querySelector('#quickHours');
function setHours(open){hoursRoll.classList.toggle('open',open);hoursRoll.setAttribute('aria-hidden',String(!open));hoursTrigger.setAttribute('aria-expanded',String(open))}
hoursTrigger.addEventListener('click',()=>setHours(!hoursRoll.classList.contains('open')));
quickHours.addEventListener('click',()=>{setHours(true);window.scrollTo({top:0,behavior:'smooth'})});
document.addEventListener('click',e=>{if(hoursRoll.classList.contains('open')&&!hoursRoll.contains(e.target)&&!hoursTrigger.contains(e.target)&&!quickHours.contains(e.target))setHours(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')setHours(false)});
function updateOpenState(){const now=new Date(),day=now.getDay(),mins=now.getHours()*60+now.getMinutes(),isOpen=day!==0&&mins>=690&&mins<1260;document.querySelector('#openState').textContent=isOpen?'Geöffnet':'Geschlossen';document.querySelector('#openDetail').textContent=isOpen?'bis 21:00':day===0?'Mo. ab 11:30':'ab 11:30';hoursTrigger.classList.toggle('is-closed',!isOpen)}
updateOpenState();
