const products=[
 {id:'spar-steak',name:'Steak Kalb Sparangebot',category:'offer',price:10,tag:'Bestseller · Sparangebot',desc:'Ganzer Steak-Döner plus Getränk. Als Dürüm +0,50 €.',image:'kalb-steak.jpg',sizes:[['Ganzer Döner',10],['Dürüm',10.5]],drinks:true,config:true},
 {id:'spar-chicken',name:'Hähnchen Sparangebot',category:'offer',price:7.5,tag:'Beliebt · Sparangebot',desc:'Ganzer Hähnchen-Döner plus Getränk. Als Dürüm +0,50 €.',image:'haehnchen.jpg',sizes:[['Ganzer Döner',7.5],['Dürüm',8]],drinks:true,config:true},
 {id:'menu-1',name:'Menü 1 · Steak',category:'menu',price:13,tag:'Premium Menü',desc:'Ganzer Steak-Döner, Pommes und Getränk. Als Dürüm +0,50 €.',image:'menu-steak-v2.jpg',sizes:[['Ganzer Döner',13],['Dürüm',13.5]],drinks:true,config:true},
 {id:'menu-2',name:'Menü 2 · Hähnchen',category:'menu',price:11,tag:'Bestseller Menü',desc:'Ganzer Hähnchen-Döner, Pommes und Getränk. Als Dürüm +0,50 €.',image:'menu-haehnchen-v2.jpg',sizes:[['Ganzer Döner',11],['Dürüm',11.5]],drinks:true,config:true},
 {id:'nugget-menu',name:'Nugget Menü',category:'menu',price:9,tag:'Menü-Angebot',desc:'Nuggets, Pommes und ein Softgetränk. Eine Dip-Soße gratis.',image:'nuggets.jpg',sizes:[['6 Nuggets',9],['9 Nuggets',10],['12 Nuggets',11]],drinks:true,sauceMode:'oneFree'},
 {id:'kids-menu',name:'Kids Menü',category:'menu',price:9.9,tag:'Für Kinder',desc:'Halber Döner oder 4 Nuggets, kleine Pommes und Capri-Sonne. Eine Dip-Soße gratis.',image:'kids-menu.jpg',sizes:[['Halber Döner',9.9],['4 Nuggets',9.9]],sauceMode:'oneFree'},
 {id:'bowl-steak',name:'Steak Döner Bowl',category:'bowl',price:13,tag:'Bowl',desc:'Steak-Dönerfleisch, Pommes und frische Zutaten.',image:'bowl.jpg',config:true},
 {id:'bowl-chicken',name:'Hähnchen Döner Bowl',category:'bowl',price:10,tag:'Bowl',desc:'Hähnchen-Dönerfleisch, Pommes und frische Zutaten.',image:'bowl-haehnchen.jpg',config:true},
 {id:'steak',name:'Kalb Steak Döner',category:'doener',price:8.5,small:5,tag:'Bestseller',desc:'Saftiges Kalb-Steakfleisch im knusprigen Brot.',image:'kalb-steak.jpg',config:true},
 {id:'chicken',name:'Hähnchen Döner',category:'doener',price:6,small:4,tag:'Klassiker',desc:'Würziges Hähnchenfleisch, frisch vom Spieß.',image:'haehnchen.jpg',config:true},
 {id:'dueruem-steak',name:'Dürüm Steak',category:'dueruem',price:9,tag:'Dürüm',desc:'Kalb-Steakfleisch eingerollt im dünnen Fladen.',image:'dueruem.jpg',config:true},
 {id:'dueruem-chicken',name:'Dürüm Hähnchen',category:'dueruem',price:6.5,tag:'Dürüm',desc:'Hähnchen und Wunschzutaten im frischen Dürüm.',image:'dueruem.jpg',config:true},
 {id:'box-steak',name:'Kalb Steak Box',category:'box',price:8.5,tag:'Box',desc:'Steakfleisch mit Pommes – ohne Salat.',image:'box-steak.jpg',config:'box'},
 {id:'box-chicken',name:'Hähnchen Box',category:'box',price:6,tag:'Box',desc:'Hähnchenfleisch mit Pommes – ohne Salat.',image:'box-haehnchen.jpg',config:'box'},
 {id:'nuggets',name:'Chicken Nuggets',category:'snack',price:4.5,tag:'Snack',desc:'Knusprige Nuggets – wahlweise 6, 9 oder 12 Stück. Dips nach Wunsch.',image:'nuggets.jpg',sizes:[['6 Stück',4.5],['9 Stück',6],['12 Stück',7.5]],sauceMode:'paidBasic'},
 {id:'pommes',name:'Pommes',category:'snack',price:4,tag:'Snack',desc:'Goldbraun und knusprig. Ketchup, Mayo oder Senf: eine Portion gratis.',image:'pommes.jpg',config:'fries',sauceMode:'oneFree'},
 {id:'extra-meat',name:'Extra Fleisch',category:'extra',price:2.5,tag:'Extra',desc:'Eine zusätzliche Portion Dönerfleisch.',icon:'🥩'},
 {id:'extra-cheese',name:'Käse',category:'extra',price:1,tag:'Topping',desc:'Herzhafter Käse als zusätzliches Topping.',icon:'🧀'},
 {id:'extra-pepper',name:'Peperoni',category:'extra',price:1,tag:'Topping',desc:'Würzige Peperoni für deinen Extra-Kick.',icon:'🌶️'},
 {id:'extra-jalapeno',name:'Jalapeños',category:'extra',price:1,tag:'Topping',desc:'Scharfe Jalapeños als zusätzliches Topping.',icon:'🫑'},
 {id:'extra-sauce',name:'Extra Soße',category:'extra',price:1,tag:'Extra',desc:'Eine zusätzliche Portion deiner Wunschsoße.',icon:'🥣',sizes:[['Knoblauchsoße',1],['Kräutersoße',1],['Cocktailsoße',1],['Scharfe Soße',1]]},
 {id:'extra-ketchup',name:'Ketchup',category:'extra',price:.5,tag:'Dip',desc:'Eine zusätzliche Portion Ketchup.',icon:'🍅'},
 {id:'extra-mayo',name:'Mayonnaise',category:'extra',price:.5,tag:'Dip',desc:'Eine zusätzliche Portion Mayonnaise.',icon:'🥚'},
 {id:'extra-mustard',name:'Senf',category:'extra',price:.5,tag:'Dip',desc:'Eine zusätzliche Portion Senf.',icon:'🟡'},
 {id:'redbull',name:'Red Bull',category:'drink',price:2.45,deposit:.25,tag:'Energy',desc:'2,45 € zzgl. 0,25 € Pfand. Verschiedene Sorten.',image:'energy.jpg'},
 {id:'softdrink',name:'Softgetränke',category:'drink',price:1.95,deposit:.25,tag:'Kaltgetränk',desc:'1,95 € zzgl. 0,25 € Pfand. Uludağ, Cola, Fanta und weitere Sorten.',image:'softdrinks.jpg'},
 {id:'fruchtsaft',name:'Capri-Sonne',category:'drink',price:1.5,tag:'Fruchtsaftgetränk',desc:'Capri-Sonne – fruchtig und gut gekühlt.',image:'fruchtsaft.jpg'},
 {id:'salgam',name:'Şalgam',category:'drink',price:2,deposit:.25,tag:'Türkischer Klassiker',desc:'2,00 € zzgl. 0,25 € Pfand. Würzig und gut gekühlt.',image:'salgam.jpg'},
 {id:'ayran',name:'Ayran',category:'drink',price:1.5,tag:'Getränk',desc:'Der erfrischende Klassiker zum Döner.',image:'ayran.jpg'},
 {id:'wasser',name:'Wasser 0,5 l',category:'drink',price:1.5,deposit:.25,tag:'Getränk',desc:'1,50 € zzgl. 0,25 € Pfand. Still oder sprudelnd.',image:'wasser.jpg'},
 {id:'kaffee',name:'Kaffee Crema',category:'drink',price:2,tag:'Heißgetränk',desc:'Festpreis 2,00 €. Milch und Zucker auf Wunsch kostenlos.',image:'kaffee.jpg',config:'coffee'},
 {id:'softdrink-1l',name:'Softgetränk 1 l',category:'drink',price:3.35,deposit:.25,tag:'Literflasche',desc:'3,35 € zzgl. 0,25 € Pfand. Verschiedene Sorten.',image:'softdrinks.jpg'}
];
